name: CI with maven + data structures + problem solving

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [21, 22, 23, 24, 25]

    steps:
    - name: Check the code
      uses: actions/checkout@v4

    - name: Set up JDK 21+
      uses: actions/setup-java@v4
      with:
        distribution: temurim
        java-version: ${{ matrix.java }}
        cache: maven

    - name: Build
        run: mvn -B clean package -DskipTests

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ matrix.java }}
        path: target/*.jar

  test:
    need: [build]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [21, 'latest']

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-${{ matrix.java }}
          path: target

      - name: Run tests
        run: mvn -B test
