name: CI with maven + data structures + problem solving

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [21, 22, 23, 24, 25]

    steps:
    - name: Check the code
      uses: actions/checkout@v4

    - name: Set up JDK 21+
      uses: actions/setup-java@v4
      with:
        distribution: temurim
        java-version: ${{ matrix.java }}
        cache: maven

    - name: build and run tests
      run: mvn test
